In [1]:
from pathlib import Path
from IPython.display import display

import pandas as pd
import numpy as np

In [2]:
paths = Path("./")

In [3]:
df_address = pd.read_csv(next(paths.glob('*address*')))
df_residential = pd.read_csv(next(paths.glob('*residential*')))

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
df_address.columns

Index(['X', 'Y', 'OBJECTID_12', 'SITE_ADDRESS_PK', 'ADDRESS_ID', 'STATUS',
       'SSL', 'TYPE_', 'ENTRANCETYPE', 'ADDRNUM', 'ADDRNUMSUFFIX', 'STNAME',
       'STREET_TYPE', 'QUADRANT', 'CITY', 'STATE', 'FULLADDRESS', 'SQUARE',
       'SUFFIX', 'LOT', 'NATIONALGRID', 'ASSESSMENT_NBHD',
       'ASSESSMENT_SUBNBHD', 'CFSA_NAME', 'HOTSPOT', 'CLUSTER_', 'POLDIST',
       'ROC', 'PSA', 'SMD', 'CENSUS_TRACT', 'VOTE_PRCNCT', 'WARD', 'ZIPCODE',
       'ANC', 'NEWCOMMSELECT06', 'NEWCOMMCANDIDATE', 'CENSUS_BLOCK',
       'CENSUS_BLOCKGROUP', 'FOCUS_IMPROVEMENT_AREA', 'SE_ANNO_CAD_DATA',
       'LATITUDE', 'LONGITUDE', 'ACTIVE_RES_UNIT_COUNT', 'RES_TYPE',
       'ACTIVE_RES_OCCUPANCY_COUNT', 'WARD_2002', 'WARD_2012', 'ANC_2002',
       'ANC_2012', 'SMD_2002', 'SMD_2012'],
      dtype='object')

In [5]:
with pd.option_context('display.max_columns', df_address.shape[1]):
    display(df_address.sample(2))

,X,Y,OBJECTID_12,SITE_ADDRESS_PK,ADDRESS_ID,STATUS,SSL,TYPE_,ENTRANCETYPE,ADDRNUM,ADDRNUMSUFFIX,STNAME,STREET_TYPE,QUADRANT,CITY,STATE,FULLADDRESS,SQUARE,SUFFIX,LOT,NATIONALGRID,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CFSA_NAME,HOTSPOT,CLUSTER_,POLDIST,ROC,PSA,SMD,CENSUS_TRACT,VOTE_PRCNCT,WARD,ZIPCODE,ANC,NEWCOMMSELECT06,NEWCOMMCANDIDATE,CENSUS_BLOCK,CENSUS_BLOCKGROUP,FOCUS_IMPROVEMENT_AREA,SE_ANNO_CAD_DATA,LATITUDE,LONGITUDE,ACTIVE_RES_UNIT_COUNT,RES_TYPE,ACTIVE_RES_OCCUPANCY_COUNT,WARD_2002,WARD_2012,ANC_2002,ANC_2012,SMD_2002,SMD_2012
57631,-77.010932,38.874241,889651,290392,290392,ACTIVE,0652 0084,ADDRESS,OFFICIAL,1315.0,NaN,HALF,STREET,SW,WASHINGTON,DC,1315 HALF STREET SW,0652,NaN,84,18S UJ 25559 04739,Old City 1,039 E Old City 1,South Washington/West of the River Collaborative,NaN,Cluster 9,Police District - First District,Police Sector 1D3,Police Service Area 105,SMD 6D06,6400.0,Precinct 127,Ward 6,20024.0,ANC 6D,NaN,NaN,006400 1008,006400 1,NaN,NaN,38.874234,-77.010930,0.0,RESIDENTIAL,1.0,Ward 6,Ward 6,ANC 6D,ANC 6D,SMD 6D06,SMD 6D06
120918,-77.051166,38.931134,952940,301372,301372,ACTIVE,PAR 00670006,PLACE,OFFICIAL,NaN,NaN,CONNECTICUT,AVENUE,NW,WASHINGTON,DC,NaN,PAR,0067,0006,18S UJ 22206 11134,National Zoological Park,NaN,Columbia Heights/Shaw Collaborative,NaN,NaN,Police District - Second District,Police Sector 2D2,Police Service Area 204,SMD 3C01,501.0,Precinct 136,Ward 3,20008.0,ANC 3C,NaN,NaN,000501 1004,000501 1,NaN,NaN,38.931127,-77.051164,0.0,NON RESIDENTIAL,0.0,Ward 1,Ward 3,ANC 3C,ANC 3C,SMD 3C01,SMD 3C01

In [6]:
df_address_column_stats = df_address.nunique().to_frame('n_unique').join(
    df_address.isna().sum().to_frame('nans')
    )

In [7]:
df_address_cols = [i for i,v in df_address_column_stats.iterrows() if v['n_unique'] < 40 and v['nans'] < 4000]
df_address_cols.append('SSL')  # join col
df_address_c = df_address[df_address_cols]

In [8]:
df_residential.columns

Index(['OBJECTID', 'SSL', 'BATHRM', 'HF_BATHRM', 'HEAT', 'HEAT_D', 'AC',
       'NUM_UNITS', 'ROOMS', 'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES',
       'SALEDATE', 'PRICE', 'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM',
       'STYLE', 'STYLE_D', 'STRUCT', 'STRUCT_D', 'GRADE', 'GRADE_D', 'CNDTN',
       'CNDTN_D', 'EXTWALL', 'EXTWALL_D', 'ROOF', 'ROOF_D', 'INTWALL',
       'INTWALL_D', 'KITCHENS', 'FIREPLACES', 'USECODE', 'LANDAREA',
       'GIS_LAST_MOD_DTTM'],
      dtype='object')

In [9]:
with pd.option_context('display.max_columns', df_residential.shape[1]):
    display(df_residential.sample(2))

,OBJECTID,SSL,BATHRM,HF_BATHRM,HEAT,HEAT_D,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,STORIES,SALEDATE,PRICE,QUALIFIED,SALE_NUM,GBA,BLDG_NUM,STYLE,STYLE_D,STRUCT,STRUCT_D,GRADE,GRADE_D,CNDTN,CNDTN_D,EXTWALL,EXTWALL_D,ROOF,ROOF_D,INTWALL,INTWALL_D,KITCHENS,FIREPLACES,USECODE,LANDAREA,GIS_LAST_MOD_DTTM
70479,69480,3751 0050,1.0,2.0,7.0,Warm Cool,Y,1.0,8.0,3.0,1954.0,NaN,1969,2.0,2013-08-23T00:00:00.000Z,310000.0,Q,1,1088,1,4.0,2 Story,8.0,Semi-Detached,3.0,Average,3.0,Average,14.0,Common Brick,1.0,Comp Shingle,6.0,Hardwood,1.0,0.0,13,3490,2018-07-22T18:01:43.000Z
45678,45679,2677 0705,3.0,1.0,13.0,Hot Water Rad,Y,2.0,6.0,4.0,1909.0,2010.0,1980,2.0,2011-03-18T00:00:00.000Z,413000.0,Q,1,1676,1,4.0,2 Story,7.0,Row Inside,4.0,Above Average,4.0,Good,14.0,Common Brick,6.0,Metal- Sms,6.0,Hardwood,2.0,0.0,24,1654,2018-07-22T18:01:43.000Z

In [10]:
df_residential_column_stats = df_residential.nunique().to_frame('n_unique').join(
    df_residential.isna().sum().to_frame('nans')
)

In [61]:
df_residential_c = df_residential.dropna(subset=['PRICE'])  # target columns
df_residential_c['YR_RMDL'] = df_residential['YR_RMDL'].fillna(-1).astype(int)
sale_date_split = df_residential_c['SALEDATE'].str.split('-', expand=True)
df_residential_c['YR_SALE'] = sale_date_split[0].astype(int)
df_residential_c['MO_SALE'] = sale_date_split[1].astype(int)
df_residential_c = df_residential_c.drop(columns=['SALEDATE'], axis=1)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [62]:
has_D = [i.split('_D')[0] for i in df_residential_c.columns if i.endswith('_D')]  # string of integer representation
df_residential_cols = [i for i in df_residential_c.columns if i not in has_D]
df_residential_cols.append('SSL') # join column

In [63]:
df_residential_c = df_residential_c[df_residential_cols]

In [85]:
df_m = df_address_c.join(df_residential_c, lsuffix='SSL', rsuffix='SSL')
df_m = df_m.drop(columns='SSLSSL', axis=1)

In [86]:
df_m_categorical = [i for i,v in df_m.dtypes.iteritems() if v == object]  # track categoricals to convert

In [87]:
df_m_dummies = pd.concat([pd.get_dummies(df_m[col]) for col in df_m_categorical], axis=1)

In [88]:
df_m = pd.concat([df_m, df_m_dummies], axis=1)
df_m = df_m.drop(columns=df_m_categorical, axis=1)

In [95]:
df_m = df_m.dropna()